# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

sudo: true
cache: packages
warnings_are_errors: false

r:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - devel

after_success:
  - Rscript -e 'covr::codecov()'

